name: Deploy to Cloudways (SSH Key)

# Alternative workflow using SSH key instead of password
# To use this workflow:
# 1. Rename this file to deploy.yml (and remove/rename the other deploy.yml)
# 2. Add SSH_PRIVATE_KEY to GitHub Secrets

on:
  push:
    branches:
      - stage
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Determine deployment target
        id: deploy-target
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "target_path=${{ secrets.SFTP_REMOTE_PATH_PROD }}" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "target_path=${{ secrets.SFTP_REMOTE_PATH_STAGE }}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Cloudways via SFTP (SSH Key)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist/*'
          remote_path: ${{ steps.deploy-target.outputs.target_path }}
          sftp_only: true
          delete_remote_files: false

      - name: Deployment notification
        run: |
          echo "✅ Successfully deployed to ${{ steps.deploy-target.outputs.environment }}"
          echo "Target path: ${{ steps.deploy-target.outputs.target_path }}"

