name: Test Workflow

on:
  push:
    branches:
      - stage
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test step
        run: |
          echo "Hello from GitHub Actions!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
